server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: login-app
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
